---
title: "Class 02: Asymptotic Analysis"
date: "01-08-2020"
---

```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

> "Think big"

Let's say we want to solve the following problem:

>> Given an array of size $n$, sort the elements in the array.

We quickly come up with a solution, but we don't know how efficient it is. We take a measure that when $n$ is $10^4$ our program takes $1$ ms to run. Given this information try to answer the following questions:

- How long will my program take to run if $n = 10 ^ 5$?
- How efficient it is to measure the performance of our code manually?
- How can we compare our solution with other solutions?
- How can we measure the performance of our code?

<div class="topic" id="contest">Sampling an Extrapolation</div>

A first approach for measuring the performance of our solution is to experimentally take time measurements for different input sizes and trying to analyze the trend that the time follows. An easy way of doing this is by plotting the input size against time to get a function we can then extrapolate. Using this method we can then experimentally compare the different algorithms we want to test, however, to do this we would have to implements all algorithms, as otherwise, it would be impossible to take times.

As you can probably imagine, this is not the most efficient process, as it is very time consuming to do this kind of testing, specially in the scenario of a time based competition as it is competitive programming. This inevitably leads to the question: is there a better way to compare our solutions?

<div class="topic" id="contest">Asymptotic Analysis</div>

A method for defining the mathematical boundaries of the run-time performance or space usage of programs as the input size increases. Useful for estimating the time and space complexity in function of the input size.

Using asymptotic analysis we can easily estimate:

- Lower Bound - $\Omega(f(n))$ Omega notation
- Upper Bound - $O(f(n))$ Big oh notation
- Tight Bound - $\Theta(f(n))$ Theta notation

In this course (and usually in competitive programming) we will only explore big oh analysis, as we usually only care about the worst possible running time of our algorithm. It is better to overestimate complexity and have a extremely fast solution than to underestimate it and have a sometimes slow one.

<div class="topic" id="contest">Big Oh Notation</div>

Big oh notation is the formal way to express the upper bound of the function that represents an algorithms running time. In practice, we will ignore all coefficients and will only care about the functions term of highest order. For example:

- $100n^2 + 1000000n + 505 = O(n^2)$
- $n^5 + 10^{100}n^4 = O(n^5)$
- $nlgn + n  = O(nlgn)$

Usually, when solving a problem, finding the big oh of a function is as simple as simplifying it to its highest order term. However, a more formal definition of big oh exists:

$$f(n) = O(g(n)) \rightarrow f(n) \leq k \cdot g(n) \quad \forall n > n_0 \, \exists k > 0$$

This definition says that a function $f(n)$ is considered to have a big oh of $g(n)$ if there exists a value of $k$ such that $k \cdot g(n)$ will be greater than $f(n)$ from some value $n_0$ of $n$ onwards. From this definition it is important to note some things:

1. Many functions $g(n)$ can satisfy the condition $f(n) = O(g(n))$
2. $O(g(n))$ can be seen as the set of all functions that are an upper-bound to function $f(n)$
3. As $O(g(n))$ represents a set, the equal operator means that the function $f(n)$ belongs to set $O(g(n))$

One of the best things about estimating performance using asymptotic analysis is that it is not necessary to implement a solution in order to check if it would work or not. This way, if we have an idea for solving a problem, we can first check if our idea is fast and within the time restrictions, and then implement it, saving us the time of implementing a wrong solution just to realize that it exceeds the time limit when is sent.

<div class="topic" id="contest">Space and Time Complexity</div>

When describing the performance of an algorithm, the word complexity is commonly used. Complexity can be considered as the amount of resources my algorithm will consume, and it comes in two ways:

- Time complexity: How long will my program take to run for a given input.
- Time complexity: How much space will my program consume for a given input.

In many cases there exists a trade-off between space-usage and run-time performance, for this reason it is important to always check the time and space complexity of a solutions before implementing it, to ensure our solutions stays within the allowed bounds.

<div class="topic" id="contest">Contest</div>

You can find the contest [here](https://vjudge.net/contest/350901).

<!-- Begins problem A -->
<div class="card">
<div class="collapsed solution-title" type="button" data-toggle="collapse" data-target="#collapseProblemA" aria-expanded="false" aria-controls="collapseTwo">
<!-- title -->
  <i class="fas fa-caret-right"></i> <p class="title">A: Bit++</p>
</div>
<!-- begin body -->
<div id="collapseProblemA" class="collapse">
<div class="card-body solution-body">

### <a href="https://codeforces.com/problemset/problem/282/A" target="_blank">Problem A: Bit++</a>

The problem is bassically to see if the input is either "X++", "++X", "---X" or "X---".

The following code use this idea. But, we only look in the middle character because that is enough to verificate.

  <!-- begin code -->
  <div class="collapsed code-title" type="button" data-toggle="collapse" data-target="#codeProblemA" aria-expanded="false" aria-controls="collapseTwo">
  <!-- title -->
  <i class="fas fa-caret-right"></i> <p class="title">Code</p>
  </div>
  <div id="codeProblemA" class="collapse">
  
```c++
#include <bits/stdc++.h>

using namespace std;

int main () {
  int n,x=0;
  cin>>n;
  string sta;
  while(n--){
	cin>>sta;
	if(sta[1]=='+')
		x++;
	else
		x--;
  }
  cout<<x<<endl;
  return (0);
}
```
  </div>
  <!-- ends code -->

</div>
</div>
</div>
<!-- ends problem A -->




<!-- Begins problem B -->
<div class="card">
<div class="collapsed solution-title" type="button" data-toggle="collapse" data-target="#collapseProblemB" aria-expanded="false" aria-controls="collapseTwo">
<!-- title -->
  <i class="fas fa-caret-right"></i> <p class="title">B: Beautiful Matrix</p>
</div>
<!-- begin body -->
<div id="collapseProblemB" class="collapse">
<div class="card-body solution-body">

### <a href="https://codeforces.com/problemset/problem/263/A" target="_blank">Problem B: Beautiful Matrix</a>

Here, we look for what is the difference between row position and column position of the 1 and the matrix's center (the matrix's center is in position 3 in axis x and y). 


So, we just need to subtract in absolute value for each axis and adding them. 

  <!-- begin code -->
  <div class="collapsed code-title" type="button" data-toggle="collapse" data-target="#codeProblemB" aria-expanded="false" aria-controls="collapseTwo">
  <!-- title -->
  <i class="fas fa-caret-right"></i> <p class="title">Code</p>
  </div>
  <div id="codeProblemB" class="collapse">
  
```c++
#include <bits/stdc++.h>

using namespace std;

int main () {
  int num;
  for(int i=1;i<6;i++){
  	for(int j=1;j<6;j++){
  		cin>>num;
  		if(num){
  			cout<<abs(i-3)+abs(j-3)<<endl;
  			i=j=6;
  		}
  	}
  }
  return 0;
}
```
  </div>
  <!-- ends code -->

</div>
</div>
</div>
<!-- ends problem B -->




<!-- Begins problem C -->
<div class="card">
<div class="collapsed solution-title" type="button" data-toggle="collapse" data-target="#collapseProblemC" aria-expanded="false" aria-controls="collapseTwo">
<!-- title -->
  <i class="fas fa-caret-right"></i> <p class="title">C: Tram</p>
</div>
<!-- begin body -->
<div id="collapseProblemC" class="collapse">
<div class="card-body solution-body">

### <a href="https://codeforces.com/problemset/problem/116/A" target="_blank">Problem C: Tram</a>

In this problem, we need to keep the maximum value of passengers in each stop. With the maximum value we can ensure the minimum capacity of the tram line.

Also, the max function is a function from Algorithm package. Do not forget, if you include bits/stdc++.h, this includes a lot of packages inside. Some of them is Algorithm, Vector, Set, Map, etc. 


  <!-- begin code -->
  <div class="collapsed code-title" type="button" data-toggle="collapse" data-target="#codeProblemC" aria-expanded="false" aria-controls="collapseTwo">
  <!-- title -->
  <i class="fas fa-caret-right"></i> <p class="title">Code</p>
  </div>
  <div id="codeProblemC" class="collapse">
  
```c++
#include <bits/stdc++.h>

using namespace std;

int main () {
  int n,a,b,temp=0,maxi=0;
  cin>>n;
  while(n--){
  	cin>>a>>b;
	temp+=b-a;
	maxi=max(maxi,temp);
  }
  cout<<max<<endl;

  return 0;
}
```
  </div>
  <!-- ends code -->

</div>
</div>
</div>
<!-- ends problem C -->




<!-- Begins problem D -->
<div class="card">
<div class="collapsed solution-title" type="button" data-toggle="collapse" data-target="#collapseProblemD" aria-expanded="false" aria-controls="collapseTwo">
<!-- title -->
  <i class="fas fa-caret-right"></i> <p class="title">D: Elephant</p>
</div>
<!-- begin body -->
<div id="collapseProblemD" class="collapse">
<div class="card-body solution-body">

### <a href="https://codeforces.com/problemset/problem/617/A" target="_blank">Problem D: Elephant</a>

For this problem, the elephant can move in steps with width of 1,2,3,4 or 5. So, it is convenient to move with the maximum allowed step if we want to minimize the number of steps to the elephant meet with its friend.

Here the maximum allowed step if the step less or equal to current distance between the elephant and its friend.

Also, we work with modular operation to calculate faster the steps.

  <!-- begin code -->
  <div class="collapsed code-title" type="button" data-toggle="collapse" data-target="#codeProblemD" aria-expanded="false" aria-controls="collapseTwo">
  <!-- title -->
  <i class="fas fa-caret-right"></i> <p class="title">Code</p>
  </div>
  <div id="codeProblemD" class="collapse">
  
```c++
#include <bits/stdc++.h>

using namespace std;

int main () {
 int x;
 int steps=0;
 cin>>x;
 for(int i=5;i>0;i--){
	if(x>=i){
		steps+=x/i;
		x%=i;
				             
    	}
 }
 cout<<steps<<endl;

  return 0;
}
```
  </div>
  <!-- ends code -->

</div>
</div>
</div>
<!-- ends problem D -->




<!-- Begins problem E -->
<div class="card">
<div class="collapsed solution-title" type="button" data-toggle="collapse" data-target="#collapseProblemE" aria-expanded="false" aria-controls="collapseTwo">
<!-- title -->
  <i class="fas fa-caret-right"></i> <p class="title">E: Even Odds</p>
</div>
<!-- begin body -->
<div id="collapseProblemE" class="collapse">
<div class="card-body solution-body">

### <a href="https://codeforces.com/problemset/problem/318/A" target="_blank">Problem E: Even Odds</a>

Firstly, the problem tells us that the sequence is all odd integers from 1 to n and then all even integers from 1 to n. 

Take care if n is even or odd. In case n is odd, we need to add one element in the odd integers block.

So, we need to calculate how many odd integers we have. Then we just check if the requested position is before or after of odd integers block.


  <!-- begin code -->
  <div class="collapsed code-title" type="button" data-toggle="collapse" data-target="#codeProblemE" aria-expanded="false" aria-controls="collapseTwo">
  <!-- title -->
  <i class="fas fa-caret-right"></i> <p class="title">Code</p>
  </div>
  <div id="codeProblemE" class="collapse">
  
```c++
#include <bits/stdc++.h>

using namespace std;

int main () {

  long long num,k;
  cin>>num>>k;
  long long aux=num/2;
  if(num%2!=0)
     aux++;

  if(k>aux)
     cout<<2*(k-aux)<<endl;
  else
     cout<<2*(k-1)+1<<endl;

  return 0;
}
```
  </div>
  <!-- ends code -->

</div>
</div>
</div>
<!-- ends problem E -->

<p style="float: none; clear: both;"></p>

<div style="float: right;" class="pt-3">	
  <a class="continue-link" href="./class-03.html" 
     data-toggle="tooltip" title="Standard Template Library">
  Next
  </a>
</div>

<div class="pt-3">
  <a class="continue-link" href="./class-01.html"
     data-toggle="tooltip" title="Introduction">
  Previous
  </a>
</div>

<script>
  $('#all-classes').collapse('show');
  $('#class-02').addClass('active');
  const cur_class = document.getElementById('class-02');
  cur_class.scrollIntoView({
    behavior: 'smooth',
    block: 'center'
  });
</script>
